// <auto-generated />
using Country.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Country.Infrastructure.Migrations
{
    [DbContext(typeof(CountryDbContext))]
    partial class CountryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Country.Infrastructure.DBEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Washington, D.C.",
                            Flag = "🇺🇸",
                            Name = "USA",
                            Population = 331002651L
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Ottawa",
                            Flag = "🇨🇦",
                            Name = "Canada",
                            Population = 37742154L
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Pretoria",
                            Flag = "🇿🇦",
                            Name = "South Africa",
                            Population = 59308690L
                        },
                        new
                        {
                            Id = 4,
                            Capital = "Windhoek",
                            Flag = "🇳🇦",
                            Name = "Namibia",
                            Population = 2540905L
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Kigali",
                            Flag = "🇷🇼",
                            Name = "Rwanda",
                            Population = 12952218L
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Berlin",
                            Flag = "🇩🇪",
                            Name = "Germany",
                            Population = 83166711L
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Paris",
                            Flag = "🇫🇷",
                            Name = "France",
                            Population = 65273511L
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Tokyo",
                            Flag = "🇯🇵",
                            Name = "Japan",
                            Population = 126476461L
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Brasília",
                            Flag = "🇧🇷",
                            Name = "Brazil",
                            Population = 212559417L
                        },
                        new
                        {
                            Id = 10,
                            Capital = "Canberra",
                            Flag = "🇦🇺",
                            Name = "Australia",
                            Population = 25687041L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
